### PR TITLE
Meson port and other improvements

### PR DESCRIPTION
**Pull request by rilian-la-te**
It is meson port and other improvements for connman-gtk to fit a GTK3 desktop.

### CODE REVIEW

**Comment by jgke** [comment]
Thanks!

Since the GTK world seems to be moving towards Meson, I guess this won't count as an additional dependency, as it comes through the rest of the packages (when building from source, at least). Could you also update README.md with the correct build and configuration instructions? I don't see any other problems right now, I'll check it out a bit more closely later.

I guess I'll have to put some patches in myself to fix those type warnings that now show up :)

**Comment by rilian-la-te** [comment]
Oh, a pleasand surprise:) I thought than this is abandoned...

It will add Meson and Ninja as dependencies. Sorry, if you cannot live with this.

Second, I want to develop a StatusNotifierItem for this, because traditional tray is deprecated. But I do not want to add any dependency.

About warnings - I know GTK some level, but I cannot use my favorite IDE with Meson (and this is an one of reason, why I am using CMake for my projects). Can I help you with it? Also I can add Russian translation (and will add it in next PR)

**Comment by jgke** [comment]
As I said (sorry for being unclear) I'm fine with the additional dependency in this case.

This isn't abandoned, I just don't use this myself since Connman itself lacks some specific corner-case features I'm using on my desktop, which NetworkManager happens to have, and my laptop's running OS X for now. ...although I could switch to Connman on my work laptop, hmm...

The system tray stuff has been deprecated for two years already, that's why its behind a conf flag, so taking it out can be done without patches if GTK actually drops the support some day - for now it works fine for everything else than Gnome itself. I had an extension for Gnome at https://github.com/jgke/gnome-extension-connman which shows basic stuff where NetworkManager put them, although it's probably broken by now - it worked in 2016 :)

The warnings are fine, I can fix them myself later.

**Comment by rilian-la-te** [comment]
Fixed README error.


> The system tray stuff has been deprecated for two years already, that's why its behind a conf flag, so taking it out can be done without patches if GTK actually drops the support some day - for now it works fine for everything else than Gnome itself. I had an extension for Gnome at https://github.com/jgke/gnome-extension-connman which shows basic stuff where NetworkManager put them, although it's probably broken by now - it worked in 2016 :)

I am not talking about GTK deprecation, I am talking about actual deprecation: KDE is switches to Wayland now - uses only SNI tray, GNOME is on Wayland now - tray is forbidden, but SNI extension exists - so, by supporting SNI it will be supported in both KDE and GNOME (and in another DEs such as MATE or Cinnamon).

So, I think SNI is future of tray)

**Comment by rilian-la-te** [comment]
Do you have another suggestions for this PR?

**Comment by jgke** [comment]
LGTM 👍  I'll shuffle the commits a bit so they look nicer, I'll push it to master soonish :)

**Comment by jgke** [comment]
And there, looks like GitHub isn't smart enough to realize this got merged, so closing by hand.

**Pull request closed without merging**
